require 'rubygems'

require 'pippi/context'
require 'pippi/check_set_mapper'
require 'pippi/report'
require 'pippi/checks/check'
require 'pippi/problem'
require 'pippi/check_loader'
require 'pippi/exec_runner'
require 'pippi/auto_runner'
require 'pippi/checks/map_followed_by_flatten'
require 'pippi/checks/reverse_followed_by_each'
require 'pippi/checks/select_followed_by_first'
require 'pippi/checks/select_followed_by_size'
require 'pippi/checks/assert_with_nil'
require 'pippi/checks/debug_check'
