require 'rubygems'

require 'pippi/context'
require 'pippi/check_set_mapper'
require 'pippi/report'
require 'pippi/tracepoint_listener'
require "pippi/checks/check"
require 'pippi/problem'
require 'pippi/check_loader'
require 'pippi/exec_runner'
require 'pippi/checks/select_followed_by_first'
require 'pippi/checks/select_followed_by_size'
require 'pippi/checks/select_followed_by_compact'
require 'pippi/checks/detect_followed_by_nil'
require 'pippi/checks/debug_check'
